# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import math

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Return(object):
    def setupUi(self, Return):
        Return.setObjectName("Return")
        Return.setEnabled(True)
        Return.resize(620, 187)
        icon = QtGui.QIcon.fromTheme("C:\\Users\\master.BASE\\Desktop\\Trust\\BDPars\\icon-192.png")
        Return.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Return)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(3, 27, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(112, 30, 400, 20))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(530, 28, 75, 23))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(112, 62, 400, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(3, 59, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_2.setFont(font)
        self.label_2.setMouseTracking(True)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 100, 601, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 150, 591, 23))
        self.progressBar.setProperty("value", 0)

        self.progressBar.setObjectName("progressBar")
        Return.setCentralWidget(self.centralwidget)

        self.retranslateUi(Return)
        QtCore.QMetaObject.connectSlotsByName(Return)
        
        print("=========PROGRESS=========")

    def retranslateUi(self, Return):
        _translate = QtCore.QCoreApplication.translate
        Return.setWindowTitle(_translate("Return", "Возврыты призыв"))
        self.label.setText(_translate("Return", "Выберете файл"))
        self.pushButton.setText(_translate("Return", "Открыть"))
        self.label_2.setText(_translate("Return", "Выберете базу"))
        self.pushButton_2.setText(_translate("Return", "Выписать"))

    '''def open_dialog_box(self):
        self.Ex_path = QFileDialog.getOpenFileName(directory="C:/Users/master.BASE/Desktop/ПРИЗЫВ")
        self.path = self.Ex_path[0]
        self.lineEdit.setText(self.path)
        print("==================TYT=================")
        print(self.path)
        print("==================TYT=================")
        return self.path'''

    def out(self):
        print("==================TYT=================")
        print(self.lineEdit_2.text())
        print("==================TYT=================")
        return self.lineEdit_2.text()